FROM registry.access.redhat.com/ubi8/nginx-118


# Add application sources
ADD luna-web/nginx.conf "${NGINX_CONF_PATH}"
ADD luna-web/nginx-default-cfg/*.conf "${NGINX_DEFAULT_CONF_PATH}"
ADD luna-web/nginx-cfg/*.conf "${NGINX_CONFIGURATION_PATH}"
ADD luna-web/*.html ./

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"