FROM quay.io/redhattraining/nginx:1.17


# Add application sources
COPY luna-web/index.html /usr/share/nginx/html/index.html

# Run script uses standard ways to run the application
CMD nginx -g "daemon off;"